### ISSUE TITLE
🎉 정리 적용 방법?

### ISSUE THREAD

**Issue by gaeng2y** [LetsSwifty/clean-code#1]
# 1. fork 뜬다

<img width="1472" alt="image" src="https://user-images.githubusercontent.com/48209839/197824589-40f8e03c-52da-4f27-b88a-48cecee6ae32.png">

# 2. 브랜치 만들기

fork 후 장마다 branch를 만든다(1장 -> chatper1, 2장 chapter2 ...)

# 3. 제목 만들기

@장_<장의 제목 snake case>(eg. 1장_깨끗한_코드)의 형태로 디렉토리를 만들고 

그 안에 chatper<몇장>.md(eg. chapter1.md>) 파일과 실습 내용은 동명의 playground 혹은 project로 만든다

# 4. 자신이 정리한 목차를 README.md에 적는다

깃헙 링크는 이런식으로 만들어두었습니다.

```
[gaeng2y]: https://github.com/gaeng2y
[nahee]: https://github.com/k-nh
[heejin]: https://github.com/heejin342
[kangddong]: https://github.com/kangddong
```

챕터 테이블 템플릿
| 챕터 X | [<장 제목>](X장_<장 제목 snake case>/chapterX.md) | | [<닉네임>][깃헙 링크] |

### README.md raw 파일로 보면 테이블 형식
```
| 챕터 번호 | <center>타이틀</center> | <center>서브 타이틀</center> | 담당자 |
|:-----:|-------|-------|:------:|
| 챕터 1 | [깨끗한 코드](1장_깨끗한_코드/chapter1.md) | | [갱이][gaeng2y] |
| 챕터 2 | [의미 있는 이름](2장_의미_있는_이름/chapter2.md) | | [갱이][gaeng2y] |
ex) (타이틀에 md파일 링크)
| 챕터 3 | [함수](3장_함수/chapter3.md) | | [갱이][gaeng2y] |
```

# 5. push 후 PR 올리기

정리가 끝났다면 푸시하고 챕터별로 **PR 올리기**

**Comment by kangddong** [comment]
LGTM 👍(이거 해보고싶었어요..ㅎ)
